# Credit for this script
# https://github.com/moodlehq/moodle-plugin-ci/issues/48
# https://github.com/moodleou/moodle-filter_embedquestion/tree/main/.github/workflows
# https://github.com/lushonline/moodle-mod_externalcontent/blob/master/.github/workflows/main.yml
name: Moodle plugin CI for Moodle 3.9 and 3.10
on: [pull_request, push]

jobs:
  test:
    runs-on: 'ubuntu-18.04'
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.2'
            moodle-branch: 'MOODLE_39_STABLE'
            database: 'mariadb'
          - php: '7.4'
            moodle-branch: 'MOODLE_39_STABLE'
            database: 'mariadb'
          - php: '7.2'
            moodle-branch: 'MOODLE_39_STABLE'
            database: 'pgsql'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

      mariadb:
        image: mariadb:10.5  # see https://tracker.moodle.org/browse/MDL-72131
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli

      - name: Deploy moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          # Add dirs to $PATH
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          # PHPUnit depends on en_AU.UTF-8 locale
          sudo locale-gen en_AU.UTF-8
      - name: Install Moodle
        run: |
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-theme_clboost.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-local_resourcelibrary.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-local_syllabus.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_featured_courses.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_mcms.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-customfield_multiselect.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_rss_thumbnails.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_forum_feed.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_enhanced_myoverview.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_thumblinks_action.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_forum_groups.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_group_members.git
          moodle-plugin-ci add-plugin --clone https://github.com/call-learning/moodle-block_sharing_cart.git --branch resourcelibrary_integration
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
          moodle-plugin-ci add-config '$CFG->customscripts = dirname(__FILE__) . "/theme/imtpn/customscripts/";'
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: phpcpd
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd || true

      - name: phpmd
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker

      - name: validate
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: mustache
        if: ${{ always() }}
        run: moodle-plugin-ci mustache || true

#      - name: grunt
#        if: ${{ always() }}
#        run: moodle-plugin-ci grunt

      - name: phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit

      - name: behat
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome --suite imtpn